# Generated by Django 5.2.4 on 2025-07-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('running_kilometers', models.PositiveIntegerField()),
                ('vehicle_type', models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback'), ('Convertible', 'Convertible'), ('Electric', 'Electric'), ('Truck', 'Truck'), ('Other', 'Other')], max_length=20)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=10)),
                ('model_year', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(default='Petrol', max_length=20)),
                ('transmission', models.CharField(default='Automatic', max_length=20)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='supercars/')),
                ('description', models.TextField(blank=True, null=True)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
