# Generated by Django 5.2.4 on 2025-07-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='spcars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car-img/')),
                ('name', models.CharField(max_length=50)),
                ('brands', models.CharField(max_length=50)),
                ('carprice', models.IntegerField()),
                ('km', models.IntegerField()),
                ('car_year', models.IntegerField()),
                ('car_typ', models.CharField(max_length=50)),
            ],
        ),
    ]
