# Generated by Django 5.2.4 on 2025-08-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supercar',
            name='vehicle_type',
            field=models.CharField(choices=[('SUV', 'SUV'), ('luxurySUVs', 'luxurySUVs'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback'), ('Convertible', 'Convertible'), ('Electric', 'Electric'), ('Truck', 'Truck'), ('Other', 'Other')], max_length=20),
        ),
    ]
